{% set name = "mosartwmpy" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8717dbce698422d8e82502614e3ad44e5ae5c70445ad9f7029f2e20e77c6046

build:
  number: 0
  noarch: python
  entry_points:
    - create_grand_parameters = mosartwmpy.utilities.create_grand_parameters:create_grand_parameters
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - bmipy >=2.0,<3.0
    - click >=8.0.1,<9.0.0
    - contextily >=1.2.0,<2.0.0
    - dask >=2021.10.0,<2022.0.0
    - geopandas >=0.10.2,<1.0.0
    - h5netcdf >=0.11.0,<1.0.0
    - hvplot >=0.7.3,<1.0.0
    - matplotlib-base >=3.4.3,<4.0.0
    - nc-time-axis >=1.4.0,<2.0.0
    - netcdf4 >=1.5.7,<2.0.0
    - numba >=0.53.1,<1.0.0
    - numpy >=1.20.3,<2.0.0
    - pandas >=1.3.4,<2.0.0
    - pathvalidate >=2.5.0,<3.0.0
    - psutil >=5.8.0,<6.0.0
    - pyarrow >=5.0.0,<6.0.0
    - pyomo >=6.2,<7.0
    - python >=3.6,<4.0
    - python-benedict >=0.24.3,<1.0.0
    - regex >=2021.10.23,<2022.0.0
    - requests >=2.26.0,<3.0.0
    - rioxarray >=0.8.0,<1.0.0
    - tqdm >=4.62.3,<5.0.0
    - xarray >=0.19.0,<1.0.0

test:
  imports:
    - mosartwmpy
    - mosartwmpy.config
  commands:
    - python -m unittest discover mosartwmpy
    - create_grand_parameters --help

about:
  home: https://github.com/IMMM-SFA/mosartwmpy
  summary: 'Python implementation of MOSART-WM: A water routing and management model'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thurber
