{% set name = "mosartwmpy" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b94cdf34269e8f65419b4a15e9401b7552adcdc8a61f3891a879c2d07e0e20b

build:
  number: 0
  noarch: python
  entry_points:
    - create_grand_parameters = mosartwmpy.utilities.create_grand_parameters:create_grand_parameters
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - bmipy ==2.0
    - click ==8.0.1
    - contextily ==1.2.0
    - dask ==2021.10.0
    - geopandas ==0.10.2
    - h5netcdf ==0.11.0
    - hvplot ==0.7.3
    - matplotlib-base ==3.4.3
    - nc-time-axis ==1.4.0
    - netcdf4 ==1.5.7
    - numba ==0.53.1
    - numpy ==1.20.3
    - pandas ==1.3.4
    - pathvalidate ==2.5.0
    - psutil ==5.8.0
    - pyarrow ==5.0.0
    - pyomo ==6.2
    - python >=3.6,<4.0
    - python-benedict ==0.24.3
    - regex ==2021.10.23
    - requests ==2.26.0
    - rioxarray ==0.8.0
    - tqdm ==4.62.3
    - xarray ==0.19.0

test:
  imports:
    - mosartwmpy
    - mosartwmpy.config
  commands:
    - python -m unittest discover mosartwmpy
    - create_grand_parameters --help

about:
  home: https://github.com/IMMM-SFA/mosartwmpy
  summary: 'Python implementation of MOSART-WM: A water routing and management model'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thurber
